### ISSUE TITLE
DotNetCliToolReference is no longer supported + .NET Core 3.1 support

### ISSUE THREAD

**Issue by dadhi** [nogic1008/T4Sample#1]
Hi here, 

Thanks for the useful example, especially for the  step-by-step guide and fir a trick with the default interface method implementation.

Could it be updated to the v3.1 and besides the `DotNetCliToolReference` is no longer supported (so the local tool config might be needed)?

**Comment by fubar-coder** [comment]
Just for other people that don't want to use the `DotNetCliToolReference`:

# Installation as local tool

## Create a tool manifest (optional)

You need a tool manifest. If you don't have one yet, please execute at solution level:

```bash
dotnet new tool-manifest
```

## Add the `dotnet-t4` local tool

```bash
dotnet tool install dotnet-t4`
```

# Initialization after clone

Install all local tools:

```bash
dotnet tool restore
```

# Preparing the project

## Updating the csproj

Just follow the instractions from the `readme` file. This is my current project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Mono.TextTemplating.Roslyn" Version="2.2.1" />
    </ItemGroup>
    
    <ItemGroup>
        <TextTemplate Include="**\*.tt" />
        <Generated Include="**\*.Generated.cs" />
    </ItemGroup>

    <Target Name="TextTemplateTransform" BeforeTargets="BeforeBuild">
        <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet t4 %(TextTemplate.Identity) -c $(RootNameSpace).%(TextTemplate.Filename) -o %(TextTemplate.Filename).Generated.cs" />
    </Target>

    <Target Name="TextTemplateClean" AfterTargets="Clean">
        <Delete Files="@(Generated)" />
    </Target>

</Project>
```

**Comment by dadhi** [comment]
@fubar-coder Cool, thank you!
Can you put that somewhere in readme? I was immediately wanted to copy that as a gist to not forget.

**Comment by fubar-coder** [comment]
@dadhi No, I cannot, because I'm not the maintainer of this repository.

**Comment by dadhi** [comment]
@fubar-coder Ohh, my bad. Then the more thanks to you!

**Comment by nogic1008** [comment]
@dadhi 
Thank you for your interest in this sample.
I wrote it before .NET Core 3.0 (now EOL) was officially released, so it may be different today.
I'll replace this repo for Current .NET version (.NET Core 3.1 & .NET 5).

@fubar-coder 
Thank you for providing the sample!!
